
all:  HSalRelAbsCons.py
	python HSalRelAbsCons.py ../examples/hsal-xml/SimpleThermo4.xml

test: testLinearAlgebra.py linearAlgebra.py
	python testLinearAlgebra.py

testex: HSalExtractRelAbs.py
	python HSalExtractRelAbs.py ../examples/hsal-xml/SimpleThermo4.xml
