#!/bin/sh
(export CLASSPATH=/export/u1/homes/bruno/projects/VVFCS/ashish-tools/hybridsal2xml:/export/u1/homes/bruno/projects/VVFCS/ashish-tools/hybridsal2xml/antlr-2.7.1/:${CLASSPATH}; java HybridSal2Xml $*)
