#!/bin/sh
java -cp "/home/ashish/tiwari/ashish-tools/hybridsal2xml:.:/home/ashish/tiwari/ashish-tools/hybridsal2xml/antlr-2.7.1:/home/ashish/tiwari/ashish-tools/hybridsal2xml/antlr-2.7.1/antlr:/usr/lib/jvm/java-6-openjdk/jre/lib/rt.jar" HybridSal2Xml $* 
