#!/bin/sh
java -cp "/home/tiwari/hs-constraints/ashish-tools/hybridsal2xml:.:/home/tiwari/hs-constraints/ashish-tools/hybridsal2xml/antlr-2.7.1:/home/tiwari/hs-constraints/ashish-tools/hybridsal2xml/antlr-2.7.1/antlr:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/rt.jar" HybridSal2Xml $* 
